# Generated by Django 4.2 on 2023-12-29 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Research',
            fields=[
                ('Research_ID', models.BigAutoField(primary_key=True, serialize=False)),
                ('Research_Title', models.CharField(max_length=300)),
                ('College', models.CharField(max_length=100)),
                ('Year', models.CharField(default=2023, max_length=20)),
                ('Date_Started', models.DateField()),
                ('Date_Ended', models.DateField()),
                ('Status', models.CharField(max_length=200)),
                ('Date_Presented', models.DateField(blank=True, null=True)),
                ('Date_Ongoing', models.DateField(blank=True, null=True)),
                ('Date_Conducted', models.DateField(blank=True, null=True)),
                ('Date_Published', models.DateField(blank=True, null=True)),
                ('ispnNo', models.CharField(blank=True, max_length=200, null=True)),
                ('Publisher_Name', models.CharField(blank=True, max_length=255, null=True)),
                ('Journal_Type', models.CharField(blank=True, max_length=255, null=True)),
                ('Journal_Index', models.CharField(blank=True, max_length=255, null=True)),
                ('Author', models.CharField(max_length=255)),
                ('Document_File', models.FileField(upload_to='documents/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Research',
                'verbose_name_plural': 'Researches',
            },
        ),
    ]
