# Generated by Django 4.2 on 2024-01-11 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ResearchTrackerApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='research',
            name='Year',
            field=models.CharField(default=2024, max_length=20),
        ),
        migrations.AlterField(
            model_name='research',
            name='updated_at',
            field=models.DateField(blank=True, null=True),
        ),
    ]
