# Generated by Django 4.2 on 2024-01-11 13:42

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('ResearchTrackerApp', '0003_alter_research_updated_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='research',
            name='updated_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
