# Generated by Django 4.2 on 2024-01-11 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ResearchTrackerApp', '0004_alter_research_updated_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='research',
            name='updated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
